project_id = "pxvembsxhwvpotydtiqa"

[functions.ai-agent-response]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.ia-default-agent]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.process-scheduled-messages]
verify_jwt = false

[functions.send-mass-campaign]
verify_jwt = true

[functions.telegram-bot-webhook]
verify_jwt = false

[functions.telegram-send-message]
verify_jwt = true

[functions.telegram-send-file]
verify_jwt = true

[functions.waha-create-session]
verify_jwt = true

[functions.waha-get-file]
verify_jwt = true

[functions.waha-get-qr]
verify_jwt = true

[functions.waha-send-message]
verify_jwt = true

[functions.waha-send-file]
verify_jwt = true

[functions.waha-session-status]
verify_jwt = true

[functions.waha-delete-session]
verify_jwt = true

[functions.waha-webhook]
verify_jwt = false

[functions.twilio-webhook]
verify_jwt = false

[functions.twilio-send-message]
verify_jwt = true

[functions.twilio-send-file]
verify_jwt = true

[functions.twilio-ai-agent-response]
verify_jwt = false
