-- ============================================================================
-- PLANES DE SUSCRIPCIÓN INICIALES - CORREGIDO PARA SUPABASE
-- ============================================================================

INSERT INTO subscription_plans (
  nombre,
  nombre_display,
  descripcion,
  precio_mensual,
  precio_anual,
  max_usuarios,
  max_contactos,
  max_mensajes_mes,
  max_sesiones_whatsapp,
  max_sesiones_instagram,
  max_sesiones_facebook,
  max_sesiones_telegram,
  max_espacios_trabajo,
  max_embudos,
  max_almacenamiento_mb,
  features,
  activo,
  orden,
  color
) VALUES
-- Plan Gratuito
(
  'free',
  'Plan Gratuito',
  'Ideal para probar la plataforma',
  0.00,
  0.00,
  1,
  100,
  500,
  1,
  0,
  0,
  0,
  1,
  2,
  100,
  '{"api_access":false,"integraciones":false,"reportes_avanzados":false,"exportar_datos":false,"whitelabel":false,"soporte":"email","canales":{"whatsapp":true,"instagram":false,"facebook":false,"telegram":false,"email":true}}'::jsonb,
  true,
  1,
  '#6B7280'
),
-- Plan Starter
(
  'starter',
  'Plan Starter',
  'Para pequeños negocios',
  29.99,
  299.00,
  3,
  1000,
  5000,
  2,
  1,
  1,
  1,
  3,
  10,
  500,
  '{"api_access":false,"integraciones":true,"reportes_avanzados":false,"exportar_datos":true,"whitelabel":false,"soporte":"email","canales":{"whatsapp":true,"instagram":true,"facebook":true,"telegram":true,"email":true}}'::jsonb,
  true,
  2,
  '#3B82F6'
),
-- Plan Pro
(
  'pro',
  'Plan Profesional',
  'Para equipos en crecimiento',
  79.99,
  799.00,
  10,
  10000,
  50000,
  5,
  3,
  3,
  3,
  10,
  50,
  2000,
  '{"api_access":true,"integraciones":true,"reportes_avanzados":true,"exportar_datos":true,"whitelabel":false,"soporte":"prioritario","canales":{"whatsapp":true,"instagram":true,"facebook":true,"telegram":true,"email":true}}'::jsonb,
  true,
  3,
  '#8B5CF6'
),
-- Plan Enterprise
(
  'enterprise',
  'Plan Enterprise',
  'Para grandes organizaciones',
  299.99,
  2999.00,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  '{"api_access":true,"integraciones":true,"reportes_avanzados":true,"exportar_datos":true,"whitelabel":true,"soporte":"dedicado","canales":{"whatsapp":true,"instagram":true,"facebook":true,"telegram":true,"email":true}}'::jsonb,
  true,
  4,
  '#F59E0B'
)
ON CONFLICT (nombre) DO NOTHING;
